[server]
headless = true
port = 8501
maxUploadSize = 500

[runner]
fastReruns = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4F8BF9"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
